theme = "nord"

[editor]
line-number = "relative"
# end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
G = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90%% -h90%% -E lazygit"
Y = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90%% -h90%% -E yazi"

[keys.normal."space"]
B = ":sh git blame -L %{cursor_line},+1 %{buffer_name} | cut -d' ' -f1 | xargs git show -s --format='%%C(yellow)%%h  %%Cgreen%%ad  %%C(bold blue)%%an  %%Creset %%s' --date=relative"
