theme = "nord"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
G = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90%% -h90%% -E lazygit"
