# JavaScript
[[language]]
name="javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }
auto-format = true
indent = { tab-width = 2, unit = "  " }

[typescript-language-server]
command = "typescript-language-server"
args = [ "--stdio" ]

# Go
[[language]]
name="go"
language-servers = [ "gopls" ]

[language-server.gopls]
command = "gopls"

# PHP
[[language]]
name = "php"
language-servers = [ "intelephense" ]
indent={ tab-width = 2, unit ="  " }

[language-server.intelephense]
command = "intelephense"
args = [ "--stdio" ]
file-types = [ "php", "inc" ]

# Elixir
[[language]]
name = "elixir"
language-servers = [ "elixir-ls" ]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[language-server.elixir-ls]
command = "elixir-ls"
