[[language]]
name="javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }
auto-format = true
indent = { tab-width = 2, unit = "  " }

[typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
